# Generated by Django 3.2.4 on 2021-11-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0004_mymodelwithfigure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mriddbb',
            old_name='Image',
            new_name='image',
        ),
    ]
